"use client";
import {useEffect,useMemo,useState} from "react";
import {Bookmark,BookmarkCheck,ExternalLink,LoaderCircle,LogOut,MapPin,RefreshCw,Search} from "lucide-react";
import {createBrowserSupabase} from "@/lib/supabase-browser";
import type {Job,JobType} from "@/lib/jobs";
type Filter="All"|JobType; type AppStatus="new"|"applied"|"action_required"|"assessment"|"interview"|"rejected"|"offer";
const statuses:AppStatus[]=["new","applied","action_required","assessment","interview","rejected","offer"];
function fromDb(x:any):Job{return{id:x.id,company:x.company,role:x.title,location:x.location||"Not disclosed",experience:[x.experience_min,x.experience_max].filter((v:any)=>v!=null).join("–")+(x.experience_min!=null?" yr":""),mode:x.work_mode||"Not disclosed",type:(x.raw_data?.type||"Testing") as JobType,fit:Number(x.match_score||x.raw_data?.fit||0),posted:x.posted_at?new Date(x.posted_at).toLocaleString():"Recently",salary:x.salary_min_lpa?`₹${x.salary_min_lpa}${x.salary_max_lpa?`–${x.salary_max_lpa}`:""} LPA`:undefined,matchedSkills:x.matched_skills||x.raw_data?.matchedSkills||[],missingSkills:x.missing_skills||x.raw_data?.missingSkills||[],requirements:x.skills||[],whyFit:x.match_reason||x.raw_data?.whyFit||"Matched to your VIP-Hunter profile.",applyUrl:x.apply_url,source:x.source}}
export default function JobDashboard({jobs:initialJobs}:{jobs:Job[]}){const sb=useMemo(()=>createBrowserSupabase(),[]);const[jobs,setJobs]=useState(initialJobs),[filter,setFilter]=useState<Filter>("All"),[query,setQuery]=useState(""),[saved,setSaved]=useState<string[]>([]),[apps,setApps]=useState<Record<string,AppStatus>>({}),[pin,setPin]=useState(""),[loading,setLoading]=useState(false),[status,setStatus]=useState("Loading…"),[email,setEmail]=useState(""),[userId,setUserId]=useState<string|null>(null),[profileId,setProfileId]=useState<string|null>(null),[authLoading,setAuthLoading]=useState(true),[sent,setSent]=useState(false);
useEffect(()=>{let alive=true;(async()=>{const{data:{session}}=await sb.auth.getSession();if(alive){setUserId(session?.user.id||null);setEmail(session?.user.email||"");setAuthLoading(false)}})();const{data}=sb.auth.onAuthStateChange((_e,s)=>{setUserId(s?.user.id||null);setEmail(s?.user.email||"")});return()=>{alive=false;data.subscription.unsubscribe()}},[sb]);
useEffect(()=>{if(!userId)return;(async()=>{setStatus("Syncing VIP-Hunter…");let{data:p}=await sb.from("user_profiles").select("id").eq("auth_user_id",userId).maybeSingle();if(!p){const{data:u}=await sb.auth.getUser();const ins=await sb.from("user_profiles").insert({auth_user_id:userId,full_name:u.user?.user_metadata?.full_name||u.user?.email?.split("@")[0]||"VIP-Hunter User",email:u.user?.email}).select("id").single();p=ins.data}if(!p){setStatus("Profile setup failed");return}setProfileId(p.id);const[m,s,a]=await Promise.all([sb.from("job_matches").select("match_score,matched_skills,missing_skills,match_reason,jobs(*)").eq("user_id",p.id).eq("eligible",true).order("match_score",{ascending:false}).limit(50),sb.from("saved_jobs").select("job_id").eq("user_id",p.id),sb.from("applications").select("job_id,status").eq("user_id",p.id)]);if(m.data?.length)setJobs(m.data.map((r:any)=>fromDb({...r.jobs,...r})));setSaved((s.data||[]).map((x:any)=>x.job_id));setApps(Object.fromEntries((a.data||[]).map((x:any)=>[x.job_id,x.status])));setStatus(`${m.data?.length||0} database matches loaded`)})()},[userId,sb]);
const visible=useMemo(()=>jobs.filter(j=>filter==="All"||j.type===filter).filter(j=>`${j.company} ${j.role} ${j.location} ${j.requirements.join(" ")}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.fit-a.fit),[jobs,filter,query]);
async function login(e:React.FormEvent){e.preventDefault();setLoading(true);const{error}=await sb.auth.signInWithOtp({email,options:{emailRedirectTo:window.location.origin}});setLoading(false);if(error)setStatus(error.message);else setSent(true)}
async function toggle(id:string){if(!profileId)return;const on=saved.includes(id);setSaved(v=>on?v.filter(x=>x!==id):[...v,id]);const q=on?sb.from("saved_jobs").delete().eq("user_id",profileId).eq("job_id",id):sb.from("saved_jobs").insert({user_id:profileId,job_id:id});const{error}=await q;if(error)setStatus(error.message)}
async function setApp(id:string,value:AppStatus){if(!profileId)return;setApps(v=>({...v,[id]:value}));const{error}=await sb.from("applications").upsert({user_id:profileId,job_id:id,status:value,applied_at:value==="applied"?new Date().toISOString():null},{onConflict:"user_id,job_id"});if(error)setStatus(error.message)}
async function refresh(){if(!pin.trim()){setStatus("Enter your private PIN");return}setLoading(true);setStatus("Searching jobs posted in the last 24 hours…");try{const r=await fetch("/api/jobs/live",{method:"POST",headers:{"x-app-pin":pin}}),d=await r.json();if(!r.ok)throw new Error(d.error||"Search failed");setJobs(d.jobs);setStatus(`${d.jobs.length} fresh matches found`)}catch(e){setStatus(e instanceof Error?e.message:"Search failed")}finally{setLoading(false)}}
if(authLoading)return <main className="center"><LoaderCircle className="spin"/> Opening VIP-Hunter…</main>;
if(!userId)return <main><section className="hero"><b className="brand">VIP-Hunter</b><h1>Your private <span>AI job hunter.</span></h1><p>Sign in by email to sync saved jobs, applications and matches across your iPhone.</p></section><form className="panel login" onSubmit={login}><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/><button disabled={loading}>{loading?"Sending…":"Send login link"}</button>{sent&&<small>Check your inbox for the secure sign-in link.</small>}</form></main>;
return <main><section className="hero"><div className="top"><b className="brand">VIP-Hunter</b><button onClick={()=>sb.auth.signOut()}><LogOut size={16}/> Sign out</button></div><h1>Fresh jobs. <span>Matched to your profile.</span></h1><p>MCA · Fresher/0–1 year · Chennai · Coimbatore · Kerala · WFO · ₹3–4 LPA target</p></section><section className="content"><div className="panel run"><div><b>24-hour job scan</b><small>{status}</small></div><input type="password" value={pin} onChange={e=>setPin(e.target.value)} placeholder="Private app PIN"/><button onClick={refresh} disabled={loading}>{loading?<LoaderCircle className="spin" size={16}/>:<RefreshCw size={16}/>} Run now</button></div><div className="stats"><div><b>{jobs.filter(j=>j.fit>=75).length}</b><span>75%+ matches</span></div><div><b>{Object.values(apps).filter(x=>x==="applied").length}</b><span>Applied</span></div><div><b>{saved.length}</b><span>Saved</span></div></div><div className="tools"><label><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search jobs…"/></label><div>{(["All","Testing","Developer","System"] as Filter[]).map(x=><button className={filter===x?"active":""} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div></div><h2>Latest matches <small>{visible.length} roles</small></h2><div className="jobs">{visible.map(job=><article key={job.id}><div className="score">{job.fit}%<small>MATCH</small></div><div className="job"><header><div><em>{job.company}</em><h3>{job.role}</h3></div><button className="icon" onClick={()=>toggle(job.id)}>{saved.includes(job.id)?<BookmarkCheck/>:<Bookmark/>}</button></header><p className="meta"><MapPin size={14}/>{job.location} · {job.experience} · {job.mode} · {job.type}</p><div className="tags">{job.matchedSkills.map(s=><span key={s}>✓ {s}</span>)}</div>{job.missingSkills.length>0&&<p className="missing"><b>Missing/unverified:</b> {job.missingSkills.join(", ")}</p>}<p>{job.whyFit}</p><footer><select value={apps[job.id]||"new"} onChange={e=>setApp(job.id,e.target.value as AppStatus)}>{statuses.map(s=><option key={s} value={s}>{s.replace("_"," ")}</option>)}</select><a href={job.applyUrl} target="_blank" rel="noreferrer">Apply manually <ExternalLink size={14}/></a></footer></div></article>)}</div></section></main>}
